### ISSUE TITLE
 ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by chemdesign-accl** [jamesgleave/Deep-Docking-NonAutomated#24]
I just want to test this program with small tests. While running sampling.py I get this error,

	 sampling: Parsed Args:
	 sampling:  - Iteration: 1
	 sampling:  - Data Directory: .../Deep-Docking-NonAutomated-main/phase_1/morgan
	 sampling:  - Training Size: 7500
	 sampling:  - Validation Size: 6000
	 sampling: Total Processes: 4
	 sampling: Starting Processes...
Traceback (most recent call last):
  File "...Deep-Docking-NonAutomated-main/phase_1/sampling.py", line 120, in <module>
    with closing(Pool(np.min([tot_process, len(f_names)]))) as pool:
  File "/home/user/anaconda3/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/user/anaconda3/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

How can I fix this?

**Comment by xavierchee** [comment]
**I also have the similar issue.**

**I used these codes:** 
`python molecular_file_count_updated.py --project_name protein_test --n_iteration 1 --data_directory /fred/oz241/xchee/[sandbox]_Deepdocking/phase_1/Morgan/library_prepared_fp --tot_process 1 --tot_sampling 3000000`

**But i get the following error:**
```
molecular_file_count_updated: Parsed Args:
         molecular_file_count_updated:  - Iteration: 1
         molecular_file_count_updated:  - Data Directory: /fred/oz241/xchee/[sandbox]_Deepdocking/phase_1/Morgan/library_prepared_fp
         molecular_file_count_updated:  - Training Size: 1
         molecular_file_count_updated:  - Validation Size: 3000000
         molecular_file_count_updated: Number Of Files: 0
         molecular_file_count_updated: Minimum Value: 0
         molecular_file_count_updated: Error: Minimum value is less than 1
         molecular_file_count_updated: Reading Files...
Traceback (most recent call last):
  File "/fred/oz241/xchee/[sandbox]_Deepdocking/phase_1/molecular_file_count_updated.py", line 68, in <module>
    with closing(Pool(min_value)) as pool:
                 ^^^^^^^^^^^^^^^
  File "/home/xchee/.conda/envs/conda_vs/lib/python3.11/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xchee/.conda/envs/conda_vs/lib/python3.11/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**However, when i check the path /fred/oz241/xchee/[sandbox]_Deepdocking/phase_1/Morgan/library_prepared_fp using list, i can see all the files:** 

smiles_all_00.txt  smiles_all_34.txt  smiles_all_68.txt
smiles_all_01.txt  smiles_all_35.txt  smiles_all_69.txt
smiles_all_02.txt  smiles_all_36.txt  smiles_all_70.txt
smiles_all_03.txt  smiles_all_37.txt  smiles_all_71.txt
smiles_all_04.txt  smiles_all_38.txt  smiles_all_72.txt
smiles_all_05.txt  smiles_all_39.txt  smiles_all_73.txt
smiles_all_06.txt  smiles_all_40.txt  smiles_all_74.txt
smiles_all_07.txt  smiles_all_41.txt  smiles_all_75.txt
smiles_all_08.txt  smiles_all_42.txt  smiles_all_76.txt
smiles_all_09.txt  smiles_all_43.txt  smiles_all_77.txt
smiles_all_10.txt  smiles_all_44.txt  smiles_all_78.txt
smiles_all_11.txt  smiles_all_45.txt  smiles_all_79.txt
smiles_all_12.txt  smiles_all_46.txt  smiles_all_80.txt
smiles_all_13.txt  smiles_all_47.txt  smiles_all_81.txt
smiles_all_14.txt  smiles_all_48.txt  smiles_all_82.txt
smiles_all_15.txt  smiles_all_49.txt  smiles_all_83.txt
smiles_all_16.txt  smiles_all_50.txt  smiles_all_84.txt
smiles_all_17.txt  smiles_all_51.txt  smiles_all_85.txt
smiles_all_18.txt  smiles_all_52.txt  smiles_all_86.txt
smiles_all_19.txt  smiles_all_53.txt  smiles_all_87.txt
smiles_all_20.txt  smiles_all_54.txt  smiles_all_88.txt
smiles_all_21.txt  smiles_all_55.txt  smiles_all_89.txt
smiles_all_22.txt  smiles_all_56.txt  smiles_all_90.txt
smiles_all_23.txt  smiles_all_57.txt  smiles_all_91.txt
smiles_all_24.txt  smiles_all_58.txt  smiles_all_92.txt
smiles_all_25.txt  smiles_all_59.txt  smiles_all_93.txt
smiles_all_26.txt  smiles_all_60.txt  smiles_all_94.txt
smiles_all_27.txt  smiles_all_61.txt  smiles_all_95.txt
smiles_all_28.txt  smiles_all_62.txt  smiles_all_96.txt
smiles_all_29.txt  smiles_all_63.txt  smiles_all_97.txt
smiles_all_30.txt  smiles_all_64.txt  smiles_all_98.txt
smiles_all_31.txt  smiles_all_65.txt  smiles_all_99.txt
smiles_all_32.txt  smiles_all_66.txt
smiles_all_33.txt  smiles_all_67.txt

**An example of a file content is:** 
ZINC000000000638_1,2,4,13,29,64,80,120,121,145,147,175,301,356,423,433,491,4
94,504,568,649,650,659,661,695,726,728,807,832,849,890,891,892,893,910,926,9
54,967,983,1019
ZINC000000000794_1,1,21,29,33,64,80,104,118,123,124,159,175,207,227,232,234,
329,356,367,386,399,428,572,582,666,695,698,705,726,773,789,807,849,861,926,
946,948,975,988

**Comment by bit-lcf** [comment]
Hello，you need to change the Data Director path with your data path （this path must has some number molecular）, because if your Number Of File is 0 , the error will be happen.see the molecular_file_count_updated.py 66-68 line
